### ISSUE TITLE
Order of transitions seems to matter

### ISSUE THREAD

**Issue by snalld** [zaceno/hyperapp-transitions#5] opened 2017-12-12 07:40 UTC
Is there any reason the order of transitions should matter?

I'm finding that the following skips the entry transition:
```
<transitions.enter time={ 500 } css={ { opacity: '0' } }>
    <transitions.exit time={ 500 } css={ _ => ({ opacity: '0' }) }>
        <div key={ id } ></div>
    </transitions.exit>
</transitions.enter>
```

but if exit is on the outside it works fine:
```
<transitions.exit time={ 500 } css={ _ => ({ opacity: '0' }) }>
    <transitions.enter time={ 500 } css={ { opacity: '0' } }>
        <div key={ id } ></div>
    </transitions.enter>
</transitions.exit>
```

Have you come across this behaviour? Is it intentional?

**Comment by zaceno** [comment] 2017-12-12 07:42
@snalld Not intentional, no -- it should be the same! Sounds like you found a bug! 👍 I'll look into it.

**Comment by zaceno** [comment] 2017-12-12 23:11
@snalld What browser & version did you notice the problem in? Also, what OS are you running (apparently in chrome 63 on windows there have been some wierd things noticed, which is troubling to me since I don't have a windows machine to work on :/)

Anyway: I made this codepen. It's the toasts example, but with your transitions above, (that wasn't working, with enter on the outside) -- and I can't seem to reproduce the issue. (Tried in chrome 63 and safari 11.0.1 on macOS Sierra) https://codepen.io/zaceno/pen/GyRemJ?editors=0010

**Comment by zaceno** [comment] 2017-12-23 15:23
@snalld Can you confirm this is still a problem? Did you look at the codepen above?

Since I can't reproduce I'm closing for now, but if it's still an issue feel free to reopen (and please, if possible, a codepen/jsfiddle demonstrating the issue)

**Closed by zaceno** 2017-12-23 15:23 UTC
Labels: bug
